### ISSUE TITLE
[1.0.3] - Negative health values

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#100]
Submitter: SPeCtator
It is possible to have a negative current health value. Any attack that deals more damage than the player has health will put player's current health below 0. Player is required to heal all the negative health to exit the Critical health mode.

Example:
Player has their health at 1.5 HP and has Double Damage item activated.
They get hit by a turret (0.5 * 2 Dmg) thier health will drop to 0.5 HP.
Getting hit by a turret again will result in their health dropping to -0.5 HP - a valid state according to the rules of the game, as the damage was not received at <= 0 HP, so the player character is still alive.
Picking up 1 health petal will heal 0.5 HP, the player then will have 0 current HP, still in Critical health mode.

The HUD will draw the current health correctly - receiving 1 health petal at -0.5 HP will not draw half of a petal on a health bar.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4.
