### ISSUE TITLE
[1.0.3] - Returning to Checkpoint from menu returns lost stocks

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#101]
Submitter: SPeCtator
Selecting "Return to Checkpoint" from the Pause menu returns the player to the previous checkpoint with the exact amount of crystals AND stocks they had when they activated the checkpoint. Makes the player being able to undo all the lost stocks in a part of a stage.

**Comment by Abel9210** [comment]
Similar bug has been reported. Closing this.

https://github.com/neonobjclash/fp2bugs/issues/43
