### ISSUE TITLE
[1.0.3] - Math error in Cheaper Stocks item

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#102]
Submitter: SPeCtator
The bar required to get the extra stock gets filled with approximately 50 more crystals every time the player dies on a stage.

The stock bar can get overfilled that way. If overfilled, 1 extra stock will be given when the player gets 1 more crystal, then the bar will reset back to 0.

**Comment by SpaceyStrife** [comment]
I think I got this one for 1.0.4. The game was subtracting 50 crystals from the "crystals to 1up" counter every restart rather than just when the stage began.
