### ISSUE TITLE
[1.0.3] - Crystal count indicator becomes glitched if over 999 crystals have been collected

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#103]
Submitter: SPeCtator
Crystal count indicator becomes glitched if the player collects over 999 crystal on a stage - possible via hitting different checkpoints back and forth and restarting.

At 1000 to 1099 the indicator shows "-##", at 1100 and more it shows "+##".
Not tested at 1200+, but the problem is clearly detected at this point.

http://imgur.com/a/k4a3Y - indicator at 1106 crystals.

**Comment by SpaceyStrife** [comment]
I've set a cap on the number of crystals the player can collect to 999. Collecting additional crystals after this will still count towards obtaining extra stocks, though.
