### ISSUE TITLE
[1.0.3] Layering hiccup → clip into terrain

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#107]
Submitter: Mylexsi
see video. very easy to reproduce. 
most other cases of this result in falling through the floor to your death, but this time i managed to clip into the terrain and got to walk around freely inside. In another place or perhaps in future in another level, this could result in skipping an entire stage.

https://youtu.be/WS70FGYeXak

**Comment by SpaceyStrife** [comment]
This was fixed up as per issue #11.
