### ISSUE TITLE
Carol´s Bike Reset

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#108]
If Carol is riding her bile during the level, and then, at any point, you pause and choose to restart the level (or choose to return to checkpoint), you begin the level with the motorcycle with you. However, if you pick up the bike, store it with the special button, and then restart the level, the bick won´t be with you at the begining, even if you try to pull it off with special again. This bug may look inoffensive, but for speedrunners and levels that doesn´t allow backtracking with the bike because of its wall climbing ability, it can break the game in half.

**Comment by Abel9210** [comment]
A similar bug has been reported. Closing this one.

https://github.com/neonobjclash/fp2bugs/issues/61
