### ISSUE TITLE
Crystal Speed Boost

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#109]
This bug works with any character. If you exit a slope (like, say, the slope at the begining of Dragon Valley, after going through the vines) at high speeds, without jumping, and then land on a crystal (the kind that gives more crystals when broken with an attack), you´ll go boosting to the right at high speeds. This even works when there´s no horizontal movement, or even when you try to go to the left when landing on the crystal. This could lead (if possible) to characters phasing through walls and even ignore enemies entirely, rendering the battles mechanic mute.

**Comment by SpaceyStrife** [comment]
Same as issue #98. Closing.
