### ISSUE TITLE
(1.0.0, 1.0.1) Can get stuck on the wrong layer and fall out of the stage.

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#11]
Submitter: johannhowitzer
Here's a bug where I stayed on the wrong layer and fell to my death.  Happened every time I cyclone jumped off this upslope.  Is still happening in 1.0.1.

https://youtu.be/YRzshMk5gMo

**Comment by SpaceyStrife** [comment]
I've added new layer switch locations that should hopefully prevent this from happening in future builds.
