### ISSUE TITLE
Lilac´s Uppercut Boost

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#111]
If you exit a slope (or exit a platform) at high speeds, without jumping, and then use Lilac´s Uppercut in the air, you´ll recive a horizontal boost and be sent at high speeds to the side you´re facing. Even if you use Lilac´s other moves (Dragon Boost, and her other attacks (Cyclone does not work)), as long you´re in the air, or even if you stop the horizontal movement, the uppercut boost will still take effect, effectively making the uppercut a broken double jump. The drawback? You can´t use the boost to go to the opposite direction of the slope, If you try that, the uppercut will work as usual, no horizontal boost. Even then, the uppercut can be used to break the game if used propelly.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4. The cause was the game always referring to Lilac's ground velocity even when airborne.
