### ISSUE TITLE
[1.0.3] After Dying Crystals respawn

### ISSUE THREAD

**Issue by RomanH1999** [GalaxyTrail/fp2bugs#112]
Yeah, as above already says, the Crystals just respawn after dying and that can be abused.
Hope there will be ways to fix it like:
- Remove collected Crystals on respawn
- Reset Crystal Counter after dying
etc.

**Comment by SpaceyStrife** [comment]
Starting from 1.0.4, KO restarts will now reset your total crystal count to what it was at your last checkpoint; however, the total crystals needed for a 1up will be retained.

This only halfway fixes the issue of course; My personal goal would be for the game to keep track of collected crystals at each checkpoint.
