### ISSUE TITLE
Standing On Top of Loop

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#115]
Submitter: aidenpons
There's one loop-de-loop that you can jump on from the right and walk across. Nothing particular needs to be done - just double-jump up on top of it, from the right. Moving to the left results in a wall. 
And you can happily jump back down afterwards.

http://i.snag.gy/Cx4RIW.jpg

**Comment by NBlastMax** [comment]
Clone of Issue #3
