### ISSUE TITLE
[1.0.3] Restart from checkpoint allows for shield mashing

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#119]
Submitter: aidenpons
This is most notable, useful, and spammable just before the boss fight.

When you restart from checkpoint, you keep your shield BUT the shield block respawns. Shields of the same type stack, even if the HUD doesn't say so. Since Restart from Checkpoint uses no lives, you can jump down, whack the shield, restart, jump down, whack the shield, jump down, restart, etc etc etc until you have a 20-health shield which makes you quite literally invincible.

**Comment by NBlastMax** [comment]
Again, issue #17 covers it.
