### ISSUE TITLE
[1.0.3] Shield HUD doesn't stack

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#120]
Submitter: aidenpons
Already have Earth Shield (2 health) + Whack another Earth Shield (+2 health) = 4 health as determined by number of hits taken, but the HUD persistently shows two, until I only have one shield health left. when it shows one.

Or are shields not supposed to stack full stop?

**Comment by NBlastMax** [comment]
I believe that Issue #17 already covers it.
