### ISSUE TITLE
[1.0.3] [Minor] Boss spawn can be delayed

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#121]
Submitter: aidenpons
By heading to the far right of the boss arena immediately, it's possible to get the Boss Warning but no boss spawn. The boss spawns when you head back to the center.

**Comment by Abel9210** [comment]
Similar report has been made before. Will be fixed in the next patch.

https://github.com/neonobjclash/fp2bugs/issues/30
