### ISSUE TITLE
'Spacehop Glitch', If you land during an attack and jump before it ends, cyclone does not refresh

### ISSUE THREAD

**Issue by ghost** [GalaxyTrail/fp2bugs#122]
https://www.youtube.com/watch?v=pXAjm-hLWNM

Also happens when you roll divekicks off of edges, or your active divekick brushes a platform but doesn't cancel its animation.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4. Also fixed with regards to Neera's double jump and Carol's pounce/bike jump.
