### ISSUE TITLE
Vine-breaking cutscene before boss plays faster on higher refresh rates

### ISSUE THREAD

**Issue by ghost** [GalaxyTrail/fp2bugs#127]
[link removed because wrong video]

Self-explanatory
https://www.youtube.com/watch?v=z2rGzseK4Jo (correct link)

**Comment by Chromatropeee** [comment]
Whoops, wrong video, here's the right one: https://www.youtube.com/watch?v=z2rGzseK4Jo

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4.
