### ISSUE TITLE
[1.0.3] [Carol] On bike, holding Down, pressing Attack causes various odd things

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#134]
Submitter: aidenpons
Obviously Carol has an attack move on her bike when holding Down and pressing Attack causes her to do a wheelie.

However, if you're not moving left or right and you hold down, press Attack, and continue to hold down, several things happen:
- Carol's sprite freezes
- Pressing Attack, Left, Right does nothing. (You expect Left and Right to do nothing, but Attack does nothing when it should just perform another attack of the same).
- Pressing Guard to boost causes Carol to boost and the Guard circle to work as normal, but the above buttons still don't work & Carol will eventually stop
- Holding a directional key and pressing Attack causes Carol to move about two pixels in the direction specified, as well as changing direction.

All of this is of course simply fixed on the player's part by stopping holding the Down key, or by pressing Up, Jump, or Special.

Meanwhile, if you do it whilst moving everything works fine & the attack can be chained.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4. The ending of the attack was checking for "regular" Carol's crouching animation which doesn't exist in Bike Carol's animation set.
