### ISSUE TITLE
[1.0.4] Carol is easily able to go on top of level boundaries.

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#139]
Submitter: Aquova
Using the jump disc and wall jump, Carol can easily go up walls and walk on top of the level geometry. If you use this to walk above the boss area, the boss fight triggers.

https://www.youtube.com/watch?v=PemB8QCBiQQ

Boss area:
https://www.youtube.com/watch?v=gLi63scK6mo

(I apologize for poor video quality and no audio, my recording setup had issues)

**Comment by SpaceyStrife** [comment]
I've adjusted the jump disc so that it's confined to the same screen boundaries as Carol and it appears to keep her from escaping. Fixed.
