### ISSUE TITLE
[1.0.1] - Max Life Up overheal on restarting

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#14]
Submitter: SPeCtator
Occures if you are playing with Max Life Up item equipped.
Selecting "Return to Checkpoint" will bring your character back to the last checkpoint with 1 more HP then they had at the moment of restarting. This additional health can go over the max health limit.
Can be used repeatedly to gain lots of health.

**Comment by SpaceyStrife** [comment]
Thanks, just fixed it so it only applies the healing when the stage first begins.
