### ISSUE TITLE
[1.0.4] Glitching through the floor while descending on vine

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#140]
Submitter: Aquova
While swinging downward on a vine, Carol was able to clip through the ground and be carried to the right. Unless the left direction was held, she was carried through the wall until she clipped out the other side. It should be noted that this was immediately after I triggered the boss fight unintentionally by going above the level area.

https://www.youtube.com/watch?v=Mp72kT6ZiRg

(I apologize for poor video quality and no audio)

**Comment by ScripScraps** [comment]
it could be used for speed running if used correctly

**Comment by TreyLina** [comment]
"SuccinctAndPunchy - Today at 1:43 AM
it's not even faster"

You just go out of bounds and can't kill the boss to end the level.

**Comment by Megalatias** [comment]
Wow, some people actually beat me up in this one, EXCEPT there's more clarification and other stuff you can do once you perform it, also, it CAN be performed with carol using the bike :P
