### ISSUE TITLE
[1.0.4] Diagonal Hangbar Glitch

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#144]
Submitter: Butters
The issue seems to be present on the moving hangbar that takes you diagonally up or down, not the still, horizontal hangbar.

https://imgur.com/a/Qpwku

**Comment by Abel9210** [comment]
Dirty fix to 'merge' the issues because you cannot do that, but this works I guess.

https://github.com/neonobjclash/fp2bugs/issues/145, https://github.com/neonobjclash/fp2bugs/issues/155

**Comment by SpaceyStrife** [comment]
... Wait a second...

![](https://i.imgflip.com/1jcazz.jpg)

Consider this fixed at last for 1.0.5.
