### ISSUE TITLE
[1.0.4][Minor] - Stocks counter does not display numbers of 10+ correctly

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#149]
Submitter: SPeCtator
If the player has over 9 stocks the stock counter will display only the last digit of the number. The actual stock number is unaffected - the player can still revive or respawn on the checkpoint after KO with "0" (really 10 / 20 / ...) stocks.

**Comment by Abel9210** [comment]
Also another dirty 'merge'.

https://github.com/neonobjclash/fp2bugs/issues/150

**Comment by SpaceyStrife** [comment]
Thought I set the stock limit to 9 but I guess not. Fixed for 1.0.5.
