### ISSUE TITLE
[1.0.4] Carol Hangbar Glitch

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#155]
Submitter: Aquova
By either using the jump disc or dash attack before landing on a hangbar, Carol appears suspending above the bar. Very easy to reproduce. 

https://i.imgur.com/RdTMaQi.png

**Comment by SpacemanStrife** [comment]
... Wait a second...

![](https://i.imgflip.com/1jcazz.jpg)
