### ISSUE TITLE
1.0.4 - Hangbar sprite misalignment bug persists with all characters

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#159]
Submitter: ItalianGamer97
Now, the consistency of the bug seems to vary by character and hangbar type, and some seem to correct themselves, while others don't. I think Lilac's seems to be able to correct itself from a brief round of testing I did with it. Might be ignored due to similar reports, but eh.

**Comment by Abel9210** [comment]
You're right. This has been reported and responded to by Strife. 

https://github.com/neonobjclash/fp2bugs/issues/144
