### ISSUE TITLE
[1.0.4][Minor] Milla handlebar graphical glitch

### ISSUE THREAD

**Issue by kivikakk** [GalaxyTrail/fp2bugs#161]
When Milla's holding onto handlebars, she's offset down a fair bit from the bar itself. Produced on Windows.

![image](https://cloud.githubusercontent.com/assets/1915/22850258/934eaf5e-f05a-11e6-9763-84088effe61c.png)

**Comment by Abel9210** [comment]
This has been reported and responded to by Strife.

https://github.com/neonobjclash/fp2bugs/issues/144
