### ISSUE TITLE
[1.0.4] [minor] lilac + bar glitch

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#165]
Submitter: Scraps Creativine
https://cdn.discordapp.com/attachments/278383783328350218/279872075731173379/meow.png 
this happens when you dragon boost into a bar unsure if it will do the same with a lower zoom

**Comment by TreyLina** [comment]
Isn't this yet another duplicate of an issue that's already resolved for the next patch?

**Comment by Abel9210** [comment]
https://github.com/neonobjclash/fp2bugs/issues/144

Also, [this.](https://cdn.discordapp.com/attachments/192833044049166337/279876243833225216/HANGBARS.png)

Please consult the [bug tracker ](https://github.com/neonobjclash/fp2bugs/issues)before making your report. It is not fun to look through what boils down to the same report sent by several different people, and it makes it harder for Strife to fix bugs.
