### ISSUE TITLE
[1.0.1] - Shield durability from stacking multiple shields

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#17]
Submitter: SPeCtator
If your character aquires a shield while already having a shield, the element of the shield will change to the one of the newest shield, but the durability of the new shield will be added to the durability of the previous shield. The effect stacks with multiple shields. The HUD does not reflect the additional durability and shows the default 2 durability points.

Example:
PC got Wood shield -> now has 2 shield durability points, wood element (HUD shows 2 points, wood).
PC got Water shield (with Wood shield intact) -> now has 4 shield durability points, water element (HUD shows 2 points, water).
PC got 1 hit of damage to the shield -> now has 3 shield durability points, water element (HUD shows 2 points, water).
PC got Earth shield -> now has 5 shield durability points, earth element (HUD shows 2 points, earth).

Maximum shield durability that can be aquired with this method is 7 points.

Also:
The current shield points remain with the character after restarting from checkpoint (but the "shield fairy" will not be visible).
This can be used, for example, to stack shield durability points from the Earth shield below the checkpoint before the boss.

**Comment by SpaceyStrife** [comment]
I was playing around with shield stacking a few days ago but I failed to wrap it up. I've went ahead and finished it.

Starting from the next build, shield points can now be stacked by breaking additional shield crystals, which will add 2 shield points to your life meter. Your maximum number of shield points will be equal to your character's maximum life petals. Additionally, shields will no longer be carried over when restarting.
