### ISSUE TITLE
[1.0.0-1.0.4] Drake Fly enemies destroy shields way too quick.

### ISSUE THREAD

**Issue by RomanH1999** [GalaxyTrail/fp2bugs#170]
It seems that when a character collides with it's flame it instantly hit so often, that it destroyes the whole shield instantly (it really doesn't matter how many lives your shield has).
https://www.youtube.com/watch?v=QPGt1PNEL_A

**Comment by Abel9210** [comment]
A similar issue has been reported.

https://github.com/neonobjclash/fp2bugs/issues/18
