### ISSUE TITLE
[1.0.4] [Windows] Neera's hangbar sprite is always out

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#177]
Submitter: aidenpons
Neera's hangbar sprite is never correctly aligned, no matter what the player does.

**Comment by NBlastMax** [comment]
-.-
There are like 4 issues closed about those. Please search though the issues before submitting.

**Comment by Abel9210** [comment]
To piggyback on this, here is the relevant issue, responded to by Strife.
https://github.com/neonobjclash/fp2bugs/issues/144
