### ISSUE TITLE
Lilac Displaced Bar Hang animation

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#191]
Submitter: Mask
Lilac seems to be copying Carol: https://postimg.org/image/664pg7zxt/

This is a repeatable bug. If you used the Dragon Boost and bounce off a wall or ceiling onto the bar, you end up displaced like this. I haven't tested it with other bars, though.

**Comment by TreyLina** [comment]
https://pbs.twimg.com/media/C4qWHzaWcAAdCid.jpg:large

This is like the...8th time it's been reported. #144
