### ISSUE TITLE
(1.0.2) Freedom Planet 2 Game Crashing Pause-Restart Glitch 

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#21]
Submitter: Noval_Chalice
https://youtu.be/OrOkMOODHAU

Published on Feb 2, 2017

This glitch happens when you restart the stage and press start right around the time the screen begins the wipe transition into gameplay. What happens is that I no longer have control of the attack button and only have access to the jump button and special.

If I move to the right side of the screen the game crashes *not shown. But as seen in the video, if I Dragon Boost to the left side of the screen, I'm under the assumption that I am breaking the game's barrier and thus killing me. This is the only way I have figured out how to prevent crashing.

I discovered this on accident while practicing on my speedruns

**Comment by SpaceyStrife** [comment]
I've created a workaround to this by disabling pausing entirely until the "Ready" prompt disappears.
