### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#214]
Submitter: Ivan 
There's a huge issue to the sample version of FP2. As soon as I start spawning into the game stage, the screen just remains black yet the game background music is playing. I can still hear the game mechanics like run, jump and attack, but just black screen and nothing else. Is the game bugged or something? Nonetheless please look further into this issue.

**Comment by Abel9210** [comment]
Need more information, this sounds like a rather rare bug. 

-What are your computer specifications? 
-Are you running the Windows or Mac version? 
-Is this consistent every time you start the game?
