### ISSUE TITLE
[1.0.4][Win] - Boss clipping through the floor when defeated

### ISSUE THREAD

**Issue by ghost** [GalaxyTrail/fp2bugs#216]
The Dragon Valley boss will clip through the floor when he takes the killing blow upon finishing his bouncing attack.
 As a result, the explosions will last forever and the player won't be able to finish the stage (which can be very painfull for speedruns).

 Video for the bug: https://www.youtube.com/watch?v=2c1XbPycEEo

 This can be reproduced with any character, but I found out Milla and Neera easier due to their huge damage outputs.

**Comment by Abel9210** [comment]
A similar issue has been reported.

https://github.com/avalice/fp2bugs/issues/186
