### ISSUE TITLE
[1.04][Win]Carol Weird Rope Grab Motorbike Animation

### ISSUE THREAD

**Issue by foxraiderpt** [GalaxyTrail/fp2bugs#217]
As the title says, if you try to grab a "rope" when using Carol with the motorbike, she does a weird animation. it was supposed to be grabbing the rope a little more down, not more above as you can see in the prints:
![gllitch 1](https://cloud.githubusercontent.com/assets/27312114/24932818/321f03ac-1f0b-11e7-9a3e-3a601f3c41eb.png)
![gllitch 2](https://cloud.githubusercontent.com/assets/27312114/24932817/321e9ee4-1f0b-11e7-8b9e-c6003d748597.png)
![gllitch 3](https://cloud.githubusercontent.com/assets/27312114/24932844/496fe896-1f0b-11e7-8beb-169480861b5f.png)

**Comment by Abel9210** [comment]
This has been reported before. 

https://github.com/avalice/fp2bugs/issues/144, https://github.com/avalice/fp2bugs/issues/177, https://github.com/avalice/fp2bugs/issues/159, https://github.com/avalice/fp2bugs/issues/155, https://github.com/avalice/fp2bugs/issues/145

**Comment by foxraiderpt** [comment]
I tought no one had posted with the motorbike tought, that´s why I posted
But thank you for being quick ^^
