### ISSUE TITLE
Carol moves along rope forever

### ISSUE THREAD

**Issue by B0M** [GalaxyTrail/fp2bugs#219]
If Carol is on a bike and she hangs on one of those bars, I can make her move along the bar left or right indefinitely regardless of how long the bar actually is. This means carol just floats and goes through walls as if the pole goes on forever. I can even get to the boundary of the stage.

When video upload is done, a visual demonstration can be seen here https://youtu.be/urida_eNNgY

**Comment by NBlastMax** [comment]
Seems to be taken care off to.
