### ISSUE TITLE
[1.0.2][Minor] The Alt+Entering of the window resets after backing to main menu

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#23]
Submitter: NBlast
Steps:
1. Set resolution to 720p
2. Alt+Enter the game
3. Return to main menu (by pause or finishing the stage.

Effect:
Window size will go back to default.

**Comment by NBlastMax** [comment]
I believe this can be closed, since you cannot Alt+Enter the screen anymore in 1.0.4
