### ISSUE TITLE
Pausing while hitting end card

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#233]
Submitter: Dusky
Email: duskydraws@gmail.com
If you pause while hitting the end card in midair, before the character starts their end animation, the pause screen will come up and the results will scroll in without sound, the victory theme will play, and if you press resume, the theme will layer on itself for a second before returning to menu. I've only done this with Carol so far but I've yet to try with the others.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.6. If the game ends up paused during the results sequence, it will freeze like everything else.
