### ISSUE TITLE
[1.0] Sample Version - Some Sound Effects Not Affected by In-Game Volume Sliders & Boss Explosion White Effect

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#24]
Submitter: Hathkar
I've noticed two sound effects not properly being influenced by the volume sliders in the menu. The two effects are the sound the green bushes make when being destroyed, and the noise the boss makes as it is destroyed and flies around the arena. I normally play with the volume sliders around 50%, and noticed the boss' explosion was very loud. I knocked the sliders down to 10%, and it was the same volume. Same results at 0%.

There's also a minor oversight when the boss is destroyed. Normally the white effect is supposed to cover the entire screen, but if you're moving at a high enough speed for the screen to pull back, you can see that the explosion is a big white square that doesn't cover the entire screen.

**Comment by NBlastMax** [comment]
This was probably fixed in >=1.0.1.

**Comment by Abel9210** [comment]
From the 1.0.1 changelog:
"Fixed one of the sound channels that wasn't being affected by the in-game Sound volume."

Closed until this can be replicated in later versions.
