### ISSUE TITLE
It is too slow...

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#246]
Submitter: Sarah
Email: nwebati@gmail.com
Hello,

Anything I do, don't work.
My game runs soooo slowly.... Even when I close discord and some others big app, or reduce the resolution...
I don't know what to do, all of my 2d games runs smoothly exept Fp2...

Here is my specs:
AMD raedon 6610 series
AMD radon r2 graphics
4 GB RAM

Thank you for responding

**Comment by calebj** [comment]
If you're watching this thread, Sarah, then go check out the latest update. It has some performance improvements that might solve this issue.

**Comment by NBlastMax** [comment]
Report rendered obsolete due to reporter playing on the previous version of the demo. Reporter responded that the FPS issues are gone in the latest version.
