### ISSUE TITLE
Suggestion: Screen Filtering Settings

### ISSUE THREAD

**Issue by Tales499** [GalaxyTrail/fp2bugs#247]
Since there's going to be more settings for Freedom Planet in a future updates, how about more for Freedom Planet 2 involving screen settings? I was thinking of adding in the following screen settings: 
**Clean**: Displays a soft game screen.
**CRT-Sharp**: Displays sharp on a cathode ray tube TV.
**CRT-Soft**: Display soft on a cathode ray tube TV.
**None**: No screen filter.

There's already an amount of people who do want to play this in the game and there's even a mod for CRT settings for the original game and adding this to the sequel would be awesome to be honest since Freedom Planet brings its inspiration from Mega Drive/Genesis games (one mainly being Sonic the Hedgehog).

**Comment by Abel9210** [comment]
Feature requests do not belong on the bug tracker.
