### ISSUE TITLE
[1.0.2][Minor] - Special meter graphical overfill

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#25]
Submitter: SPeCtator
If player character's special meter is full and they collect crystals (or petals at full health), the special meter's blue bar will overfill, going beyond its orange frame. After several frames it resets to its correct maximum length.

Does not work with Milla as her special meter is not refilled with crystals.

**Comment by SpaceyStrife** [comment]
Just fixed it by locking the energy meter's sprite to a maximum width of 1.0.
