### ISSUE TITLE
[1.0.2] - Inputting the move left and right commands simultaneously

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#26]
Submitter: SPeCtator
If player holds down keys for moving left and moving right at the same time, the player character will be moving at moderately slow speed to the direction that was pressed first.
If the key for moving left was pressed first, the player character will be moonwalking to the left.

**Comment by Abel9210** [comment]
A similar bug has been reported here:
https://github.com/neonobjclash/fp2bugs/issues/9

Closing this, but do keep reporting, I like your bug reports.
