### ISSUE TITLE
[1.0.1] Carol/Neera double special move, if meter is available

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#27]
Submitter: Zzzzzx
If your meter is rapidly refilling as Carol/Neera they can throw a second projectile immediately after the first (2 discs/freezers).  Main case that this will happen is when opening a chest that gives 50 crystals.

**Comment by SpaceyStrife** [comment]
I've adjusted the chests so that they don't cause energy recovery. I've also halved the amount of energy recovered from crystals in general which should reduce the likelihood of double specials in areas with lots of crystals to collect out in the open.
