### ISSUE TITLE
Out of bounds, leads to other areas not intended.

### ISSUE THREAD

**Issue by Teutonicknight2** [GalaxyTrail/fp2bugs#298]
**-How did it happen?** Just playing through near the boss, backtracking on my own just cus'.
**-What were you doing at the time?** Read above.
**-What is your operating system?** Windows 10
**-What are your computer's specs?** 'Dunno.
**-How easy is this to reproduce?** On a scale of 1-10, probably 9. Really easy.
**-Can this happen with anyone else?** Most likely!
**-Is this actually for FP2?** Totally.

Let me start with this. There's a vine plant near three springs right next to the boss's arena, aiming diagonally at it. To do this glitch, take the upmost spring, and don't jump off the vine, Keep holding right, You should do one of 4 things; 
-go through the wall going right (going all the way right can kill anyone who is not Carol)
-through the floor (be careful, this can kill you too, but you can revive... for some reason)
-slightly stuck, but easily unstuck when releasing the button or jumping
-nothing, attempt the glitch again
![screen_10](https://user-images.githubusercontent.com/43461330/45861138-b0609680-bd30-11e8-8738-335d00f6baea.png)
![screen_11](https://user-images.githubusercontent.com/43461330/45861139-b0609680-bd30-11e8-98d6-67ca06f106ca.png)
![screen_16](https://user-images.githubusercontent.com/43461330/45861140-b0609680-bd30-11e8-844e-767770e689a7.png)

When you go through the cave and the wall going right, you can essentially fall to your death after you get to the end of the tiles, but if you are playing as Carol, you can actually climb over the boss's arena, with a random chance of him activating! (I have a recorded rather rubbish video of this in action)

Why does this glitch happen? I think it's because the vine's release hitbox is simply too close to the ground, especially compared to some **other trees that aren't close enough!**
![screen_13](https://user-images.githubusercontent.com/43461330/45861194-df770800-bd30-11e8-81a2-8ab2d11358dc.png)

With Lilac, you can even reach the very far end of the level, but...
![screen_18](https://user-images.githubusercontent.com/43461330/45861178-cd956500-bd30-11e8-8ae6-1191b90213c9.png) Yeah, not much here besides trees, ha.

**Comment by Abel9210** [comment]
https://github.com/GalaxyTrail/fp2bugs/issues/58
https://github.com/GalaxyTrail/fp2bugs/issues/78
https://github.com/GalaxyTrail/fp2bugs/issues/97
https://github.com/GalaxyTrail/fp2bugs/issues/140

**Comment by Teutonicknight2** [comment]
Didn't realize I duped 4 glitches at the same time, my bad! But is the one with the revive option a new bug?

**Comment by Abel9210** [comment]
The revive thing is a new consequence of the bug that I haven't seen before, but this is still just the same bug.

**Comment by Teutonicknight2** [comment]
It basically happens when you hit the bottom of the screen while you are in the tiles, and the game will push you back up.

**Comment by IffyBog** [comment]
Can't seem to replicate it for some reason.....

**Comment by Teutonicknight2** [comment]
> Can't seem to replicate it for some reason.....

My version might be different,I forgot that little detail. Mine is 1.0.6. It may depend on that, which part of the glitch are you trying to do?
