### ISSUE TITLE
[1.0.2] - Small size of Boss summoning trigger area

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#30]
Submitter: SPeCtator
If the player character enters the boss arena holding to the right side, they will not hit the area that triggers the boss appearing and will be standing on an empty arena with no BGM.
The boss can still appear whenever the player character crosses the area somewhere closer to the middle of the arena (including the ceiling).

**Comment by SpaceyStrife** [comment]
I've doubled the summoning area for 1.0.4, so hopefully that does the trick.
