### ISSUE TITLE
[1.0.2] Floor Collision Bug

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#32]
Submitter: Zzzzzx
In the area right after the bonus ring, if you jump off the rising part of the slope and have a way to gain enough horizontal distance without touching the ground, you will fall through the floor and fall to your death.  Hitting a solid platform from below during this will cause the bug to not occur.

https://www.youtube.com/watch?v=SayWbL0Fdc8
(can be done with dragon boost too)

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4.
