### ISSUE TITLE
[1.0.1] Softlock after beating the boss

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#36]
Submitter: Fladervy
After beating the boss, it dies under the stage and proceeds to bounce around, but outside the arena. The boss never stops to bounce around, softlocking the stage.
This is likely related to beating it while on ball form and near the ground.
Worth noting too that the impact from hitting the ground did 5x as much damage as usual.

**Comment by NBlastMax** [comment]
@Abel9210 This probably could be closed as for the new patch.
