### ISSUE TITLE
Game extremely slow on monitors with higher refresh rate

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#37]
Submitter: HDL
Using a 120 or 144 Hz monitor causes characters in-game to move and animate incredibly slowly.  Lowering the refresh rate of the monitor while the game is active will make everything, including menus, perform significantly slower.

**Comment by Abel9210** [comment]
This issue should have been addressed in ver. 1.0.3. Can you confirm that it was fixed on that version?

**Comment by SpaceyStrife** [comment]
I've received confirmation that it's fixed in 1.0.3.
