### ISSUE TITLE
[1.0.3] Black screen when double-clicking the title bar

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#41]
Submitter: Zzzzzx
Double clicking the title bar of the game window will resize the game and cause it to have a black screen.

**Comment by ghost** [comment]
I can reproduce this issue on 1.0.3. Changing video modes restores screen painting if you happen to be in the Options menu already.

**Comment by SpaceyStrife** [comment]
While it would be nice if I could figure out smooth resizing at some point, I've disabled the ability to resize by dragging, and the game will keep itself locked into the resolution chosen through Settings in case it is accidentally maximized.
