### ISSUE TITLE
All characters will not die against the boss until 1 hit after the health meter runs out.

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#42]
Submitter: Butters
I have reported this bug before on version 1.0.1, but I didn't see it in this list (though strangely, the Milla bracelet one I also reported is) and I ran into it again in 1.0.3, so I'm reporting it again here as this is a major bug that needs fixing.

In the link below, I got the bug in action. While this does work with all characters, I recorded it using Carol. My reasoning for using her was because when I wasn't recording and just playing around with the demo, the bug was at its worst with me dying 2 hits after my health meter ran out. I tried to duplicate that as you'll see in the video, but I couldn't get it to work. However, I did manage to survive after my health meter ran out in all 3 attempts in the video.

http://streamable.com/2str7

**Comment by SpaceyStrife** [comment]
This behavior is intentional - The player can not be knocked out unless they're hit with no petals. I would like to add a visual cue that makes this feel more intentional, such as making the meter glow red when all petals are gone.
