### ISSUE TITLE
(V 1.0.3)Regaining lives prior to game over screen

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#43]
Submitter: Noval_Chalice
Normally when you run out of lives due to an enemy/boss and you are sent to the game over screen and the prompt to restart the stage is given. This bug is basically hitting start when you get the "defeated" icon and hit "restart from checkpoint". Once you do that, you restart to the checkpoint with all your stock regained. 

This bug has been present in all versions

Video Reference: https://youtu.be/4naqqFlpTlc

**Comment by SpaceyStrife** [comment]
It seems that "Return to Checkpoint" is overall problematic when it comes to player deaths, so as a workaround, I've made it so that the option is locked while the player is knocked out.
