### ISSUE TITLE
[1.0.3][Minor] Deadzone on gamepad sticks is really low while reconfiguring controls

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#49]
Submitter: NBlast
Using X360 pad when rebinding controls.

Trying to rebind buttons may result in accidentally putting an pad's stick motion, since it detects even slightest deviations from the [0,0] as a input. Setting inputs is possible, but the more worn out pad may be it, can be harder to put the stick into neutral. This may result in people unable to rebind controls

Deadzone on stick motions in settings menu should be higher, so only bold, decisive motion of the stick will put the input on the map.

**Comment by SpaceyStrife** [comment]
I've attempted a fix by only checking for axis inputs above 0.5 (with 1 being full input). I don't have a controller that experienced this issue so I'll leave this open until the next build is out and we have confirmation.

**Comment by NBlastMax** [comment]
Awesome. I'm more than happy to check this out when 1.0.4 hits.

**Comment by NBlastMax** [comment]
I can report that Control Setting menu have a proper deadzone in 1.0.4. Just according to keikaku.

Can be closed.

**Comment by SpaceyStrife** [comment]
(Translator's note: keikaku means plan)
