### ISSUE TITLE
Incorrect resizing when maximizing the window during the Unity splash screen. (Version 1.0.3)

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#50]
Submitter: Entity1037
If I click maximize on the game window during the Unity splash screen, then when it gets to the Galaxy Trail screen it'll reduce its size again to default, while still displaying the minimize icon on the window. Moving the window at all causes it to display the correct icon and enlarge to the original size it had during the Unity splash screen.

**Comment by SpaceyStrife** [comment]
Window resizing will be disabled for 1.0.4 so this should no longer be an issue at that point.
