### ISSUE TITLE
(1.0.1) Game FPS tied to screen refresh rate

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#6]
Submitter: Chromatrope
Game FPS still tied to screen refresh rate, but not directly anymore.
120hz - plays at 60fps but suffers from sporadic framedrops and severe stuttering during camera zoomout.
144hz - plays at 72fps and suffers from the above as well.

**Comment by SpaceyStrife** [comment]
Fixed in 1.0.2.
