### ISSUE TITLE
[1.0.3][Minor] - Carol unable to reach health petals on Boss checkpoint without jumping

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#65]
Submitter: SPeCtator
It seems like Carol is unable to reach the health at the Boss checkpoint without jumping. She is just short enough to run underneath it. Other characters can collect this health without jumping, IIRC.

http://imgur.com/a/Qzu6M - on foot
http://imgur.com/a/tl65K - on motorcycle

**Comment by SpaceyStrife** [comment]
It seems that it was being caused by Carol's fastest running animation, which reduced the height of her hitbox and didn't change it back. I've gone through and made sure that all of Carol's animations make proper adjustments to her hitbox size.
