### ISSUE TITLE
[1.0.3][Minor] - Carol unable to reach health petals on Boss checkpoint without jumping addendum

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#66]
Submitter: SPeCtator
Additional note to issue #65.

This bug occurs if you play through the stage from beginning to this problematic segment in one go. Restaring on this checkpoint causes the game to remember Carol's correct height and allows her to pick up the health without jumping.

Possible cause of "the shortening" is unknown to me.
Tested picking up the Gas canister and latching onto a vine; results are negative.

**Comment by SpaceyStrife** [comment]
It seems that it was being caused by Carol's fastest running animation, which reduced the height of her hitbox and didn't change it back. I've gone through and made sure that all of Carol's animations make proper adjustments to her hitbox size.
