### ISSUE TITLE
[1.0.3] Lilac cyclone after air dragon boost

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#77]
Submitter: Zzzzzx
There is some inconsistency with using the mid-air action after a dragon boost.  After using a ground dragon boost Lilac can use either an uppercut or a cyclone, even if she ends up in the air after boosting.  After using an air dragon boost Lilac can use an uppercut but not a cyclone.  Basically she should be able to cyclone since she still has a mid-air action available to her.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4. Lilac will be able to cyclone out of a Dragon Boost in both cases.

I originally disabled cyclones after boosting because it would send you flying ridiculously far, but it seems that the fix for the pause-buffered cyclone prevents this from happening now.
