### ISSUE TITLE
[1.0.3] - FP2 1.0.3 - Skipping the GT cutscene after certain point doesn't skip the audio.

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#90]
Submitter: Fladervy
https://youtu.be/0uPp5byMYJA

Skipping the GalaxyTrail cutscene after AAA presses the button doesn't stop the X fall sound and the GT logo sound. AAA's voiceover is stopped as expected, however.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4.
