### ISSUE TITLE
[1.0.3] - Returning to checkpoint upon defeat

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#91]
Submitter: Fladervy
https://youtu.be/XOg7_TRiRK8

Upon defeat (dead and no stocks), it's still possible to return to a previous checkpoint. This ruins the meaning of game overs if untouched.

**Comment by Abel9210** [comment]
This has been addressed by Strife. Will be fixed in the next version.

https://github.com/neonobjclash/fp2bugs/issues/43
