### ISSUE TITLE
[1.0.3] Same frame jump+attack while looking up and standing still results in a High Uppercut

### ISSUE THREAD

**Issue by ghost** [GalaxyTrail/fp2bugs#93]
This keeps the double jump slot because the uppercut, by being same-frame with the jump, is grounded. A cyclone can also be chained from the launch for massive height. Bad, annoying tech, deserves to be patched out. https://www.youtube.com/watch?v=rnDIMA7PtyE

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4; The jumping action will take priority.
