### ISSUE TITLE
[1.0.3] [Minor] Moonwalking!

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#95]
Submitter: Mylexsi
Hold Left + Right at the same time.
You get either a moonwalk to the left, or an ordinary-but-slow walk to the right, depending on which direction you pressed first.

https://www.youtube.com/watch?v=q5LzyaEhZR0

**Comment by Abel9210** [comment]
Similar reports have been made. Closing this one.

https://github.com/neonobjclash/fp2bugs/issues/26, https://github.com/neonobjclash/fp2bugs/issues/9
